In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

### Creating 1-D Array:

In [2]:
arr1d=np.array([1,2,3,4,5])
print("This is 1-D array:",arr1d)

This is 1-D array: [1 2 3 4 5]


### Creating 2-D Array:

In [3]:
arr2d=np.array([[1,2,3,4],
                [1,2,3,4],
                [1,2,3,4],
               ])
print("This is 2-D array:\n\n",arr2d)

This is 2-D array:

 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


### Creating 3-D or Multi-D Array:

In [4]:
arr3d=np.array([[[1,2,3,4],
                [1,2,3,4],
                [1,2,3,4],
               ],
               [[1,2,3,4],
                [1,2,3,4],
                [1,2,3,4],
               ],
                [[1,2,3,4],
                [1,2,3,4],
                [1,2,3,4],
               ]])
print("This is 3-D array:\n\n",arr3d)

This is 3-D array:

 [[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


### Use of type() function:
- It will give the type of object.


In [5]:
print("type of array 1-D array:",type(arr1d))

type of array 1-D array: <class 'numpy.ndarray'>


### Use of ndim:
- It will give the dimention of NumPy array.

In [6]:
print("Dimention of Array arr1d:->",arr1d.ndim)
print("Dimention of Array arr2d:->",arr2d.ndim)
print("Dimention of Array arr3d:->",arr3d.ndim)

Dimention of Array arr1d:-> 1
Dimention of Array arr2d:-> 2
Dimention of Array arr3d:-> 3


### Use of shape:
- It will give you shape of array.

In [7]:
print("Shape of array arr1d will be: ", arr1d.shape)
print("Shape of array qrr2d will be:", arr2d.shape)
print("Shape of array arr3d will be:", arr3d.shape)

Shape of array arr1d will be:  (5,)
Shape of array qrr2d will be: (3, 4)
Shape of array arr3d will be: (3, 3, 4)


*** 
### Data Types in Python
- By default Python have these data types:
    - strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
    - integer - used to represent integer numbers. e.g. -1, -2, -3
    - float - used to represent real numbers. e.g. 1.2, 42.42
    - boolean - used to represent True or False.
    - complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j 
***

***
### Data Types in NumPy
- NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

    Below is a list of all data types in NumPy and the characters used to represent them.

    - i - integer
    - b - boolean
    - u - unsigned integer
    - f - float
    - c - complex float
    - m - timedelta
    - M - datetime
    - O - object
    - S - string
    - U - unicode string
    - V - fixed chunk of memory for other type ( void )

***
- <H4>Use of dtype:</H4>
    - It give what kind of data means type of data we are using.

In [8]:
print("Data type of array arr1d:", arr1d.dtype)
print("Data type of array arr1d:", arr2d.dtype)
print("Data type of array arr1d:", arr3d.dtype)

Data type of array arr1d: int64
Data type of array arr1d: int64
Data type of array arr1d: int64


In [9]:
arr = np.array(['apple', 'banana', 'cherry'])

print("Data type of array arr:", arr.dtype)

Data type of array arr: <U6


- Create an array with data type string:

In [10]:
arr = np.array([1, 2, 3, 4], dtype='S')

print("Here is array:",arr)
print("Data type of array arr:", arr.dtype)


Here is array: [b'1' b'2' b'3' b'4']
Data type of array arr: |S1


 ## Note: For i, u, f, S and U we can define size as well.

- Create an array with data type 4 bytes integer:

In [11]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


- There is diffrence between type of value and given type.
- that's why error.

***
#### Converting Data Type on Existing Arrays
- The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

- The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.


***

- Change data type from float to integer by using **"i" as parameter value:**

In [12]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print("New array with int value",newarr)
print("Old Data type:",arr.dtype)
print("New data type:",newarr.dtype)

New array with int value [1 2 3]
Old Data type: float64
New data type: int32


- Change data type from float to integer by using **int as parameter value:**

In [13]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print("New array with int value",newarr)
print("Old Data type:",arr.dtype)
print("New data type:",newarr.dtype)

New array with int value [1 2 3]
Old Data type: float64
New data type: int64


In [14]:
arr = np.array([1, 0, 3.1])

newarr = arr.astype(bool)

print("New array with int value",newarr)
print("Old Data type:",arr.dtype)
print("New data type:",newarr.dtype)

New array with int value [ True False  True]
Old Data type: float64
New data type: bool


In [15]:
flaotarr=np.array([1.0,2,3,4])
strarr=np.array(["this","is","bhawan"])
strflaotintarr=np.array([1,2,3.5,"bhawan"])

print("Data type of float value array:",flaotarr.dtype)
print("Data type of str value array:",strarr.dtype)
print("Data type of mix value array:",strflaotintarr.dtype)

Data type of float value array: float64
Data type of str value array: <U6
Data type of mix value array: <U32


### Use of Ones():
- Python numpy.ones() function returns a new array of given shape and data type, where the element’s value is set to 1.

- **Syntex:** <H3>ones(shape, dtype=None, order='C')</H3>

In [16]:
onesarr=np.ones((2,2))
print("Ones array:\n",onesarr)

############################

print("\n#### Change in type of array:")
onesarr=np.ones((4,4),dtype=int)
print("\nOnes array:\n",onesarr)

onesarr=np.ones((4,4,3),dtype=int)
print("\nOnes array 3-D\n",onesarr)

###########################

print("\n#### MIX value type of array:")
onesarr=np.ones((3,3),dtype=[('x',int),('y',float)])
print("\nOnes array:\n",onesarr)


Ones array:
 [[1. 1.]
 [1. 1.]]

#### Change in type of array:

Ones array:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Ones array 3-D
 [[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]

#### MIX value type of array:

Ones array:
 [[(1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.)]]


### Use of Zeros():
- Return a new array of given shape and type, filled with zeros.

- **Syntex:** <H3>numpy.zeros(shape, dtype=float, order='C', *, like=None)
</H3>

In [17]:
zrerosarr=np.zeros((3,3))
print("Zeros array:\n",zrerosarr)

############################

print("\n#### Change in type of array:")
zrerosarr=np.zeros((4,4),dtype=int)
print("\nZeros array:\n",zrerosarr)

zrerosarr=np.zeros((4,4,3),dtype=int)
print("\nZeros array 3-D\n",zrerosarr)

###########################

print("\n#### MIX value type of array:")
zrerosarr=np.zeros((3,3),dtype=[('x',int),('y',float)])
print("\nO's array:\n",zrerosarr)


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

#### Change in type of array:

Zeros array:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Zeros array 3-D
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]

#### MIX value type of array:

O's array:
 [[(0, 0.) (0, 0.) (0, 0.)]
 [(0, 0.) (0, 0.) (0, 0.)]
 [(0, 0.) (0, 0.) (0, 0.)]]


### Use of empty():
-Return a new array of given shape and type, without initializing entries.
- **Syntex:** <H3>numpy.empty(shape, dtype=float, order='C', *, like=None)
</H3>


In [18]:
emptyarr=np.empty((3,3))
print("Empty array:\n",emptyarr)

print("\n###################################################################################")

print("\n#### Change in type of array:")
emptyarr=np.empty((3,3),dtype=int)
print("\n Empty array:\n", emptyarr)

emptyarr=np.empty((3,3,3),dtype=int)
print("\n Empty array 3-D\n", emptyarr)

print("\n###################################################################################")

print("\n#### MIX value type of array:")
emptyarr=np.empty((3,3),dtype=[('x',int),('y',float)])
print("\n Empty array:\n",emptyarr)


Empty array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

###################################################################################

#### Change in type of array:

 Empty array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

 Empty array 3-D
 [[[94536796243968              0 10020158701575]
  [             0    17179869187              0]
  [             0   137438953494              0]]

 [[             0              0              0]
  [             0              0              0]
  [             0              0              0]]

 [[             0              0              0]
  [             0 94536801903520 94536801903936]
  [94536801904192              0              0]]]

###################################################################################

#### MIX value type of array:

 Empty array:
 [[( 94536802550064, 0.00000000e+000) (140088178245232, 6.92132939e-310)
  (140089267180528, 6.92132939e-310)]
 [(140088178245168, 6.92132939e-310) (140088178245104, 6.92132939e-310)
  (140088

### Use of empty_like():
- Return a new array with the same shape and type as a given array.
- **Syntex:** <H3>numpy.empty_like(prototype, dtype=None, order='K', subok=True, shape=None)
</H3>


In [19]:
arr2d=np.array([[1,2,3,4],
                [1,2,3,4],
                [1,2,3,4],
               ])

emptyarr_like=np.empty_like(arr2d)
print("Empty array:\n",emptyarr_like)

print("\n Type of empty_like:",emptyarr_like.dtype)

print("\n###################################################################################")

print("\n#### Change in type of array:")
emptyarr_like=np.empty_like(arr2d,dtype=float)
print("\n Empty array:\n", emptyarr_like)

print("\n###################################################################################")

print("\n#### MIX value type of array:")
emptyarr_like=np.empty_like(arr2d,dtype=[("x",int),("y",float)])
print("\n Empty array:\n",emptyarr_like)

print("\n###################################################################################")

print("\n#### Change in Subok and Shape:")

emptyarr_like=np.empty_like(arr2d,dtype=float,subok=False,shape=(4,3))
print("\n Empty array:\n", emptyarr_like)

Empty array:
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

 Type of empty_like: int64

###################################################################################

#### Change in type of array:

 Empty array:
 [[4.67073870e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [6.92110147e-310 9.58873507e-043 7.24898036e+169 4.42905953e+175]
 [2.98592350e-032 1.25780474e-071 1.04874283e+165 7.31975365e+169]]

###################################################################################

#### MIX value type of array:

 Empty array:
 [[(4596373779694328218, 0.2 ) (4603579539098121011, 1.  )
  (                  0, 0.6 ) (4607182418800017408, 1.  )]
 [(                  0, 0.8 ) (4600877379321698714, 1.  )
  (4607182418800017408, 1.  ) (4603579539098121011, 1.  )]
 [(4602678819172646912, 0.36) (4599616371426034975, 1.  )
  (4607182418800017408, 1.  ) (4607182418800017408, 1.  )]]

###################################################################################

#### Change in Subok

### Use of full():
- Return a new array of given shape and type, filled with fill_value.
- **Syntex:** <H3>numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)</H3>